"on":
    push:
        branches:
            - main
name: Deploy to go-getting-started
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: porter apply
              env:
                PORTER_APP_NAME: go-getting-started
                PORTER_CLUSTER: "1"
                PORTER_DEPLOYMENT_TARGET_ID: af04fbf5-a48f-49b6-86ec-3291bfc75c83
                PORTER_HOST: https://witt.withporter.run
                PORTER_PROJECT: "1"
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_1_1084533711 }}
